"use client";

import { FormEvent, useEffect, useState } from "react";
import { activatePipeline, createPipeline, deletePipeline, exportPipelines, importPipelines, listPipelines, Pipeline } from "@/lib/auth-api";

export function PipelinePanel({ projectId, accessToken }: Readonly<{projectId: string; accessToken: string}>) {
  const [items, setItems] = useState<Pipeline[]>([]); const [error, setError] = useState("");
  useEffect(() => { void listPipelines(accessToken, projectId).then(setItems).catch((reason: Error) => setError(reason.message)); }, [accessToken, projectId]);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const configuration = {retrieval_mode: String(data.get("mode")) as "hybrid" | "vector" | "keyword", top_k: Number(data.get("topK")), similarity_threshold: Number(data.get("threshold")), rerank: data.get("rerank") === "on"}; void createPipeline(accessToken, projectId, {name: String(data.get("name")), configuration}).then((item) => setItems((current) => [item, ...current])).catch((reason: Error) => setError(reason.message)); }
  function download() { void exportPipelines(accessToken, projectId).then((blob) => { const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "flowraga-pipelines.json"; link.click(); URL.revokeObjectURL(url); }); }
  function upload(file?: File) { if (!file) return; void file.text().then(JSON.parse).then((data) => importPipelines(accessToken, projectId, data)).then((created) => setItems((current) => [...created, ...current])).catch(() => setError("Invalid pipeline export file")); }
  return <section className="pipeline-panel"><p className="eyebrow">Pipeline builder</p><h2>Configure a reliable RAG flow</h2><div className="pipeline-flow"><span>Documents</span><span>Retrieve</span><span>Rerank</span><span>Generate</span><span>Evaluate</span></div><form onSubmit={submit}><input name="name" required maxLength={120} placeholder="Pipeline name" /><select name="mode" defaultValue="hybrid"><option value="hybrid">Hybrid retrieval</option><option value="vector">Vector retrieval</option><option value="keyword">Keyword retrieval</option></select><input name="topK" type="number" min="1" max="20" defaultValue="5" aria-label="Top K" /><input name="threshold" type="number" min="0" max="1" step="0.05" defaultValue="0.25" aria-label="Similarity threshold" /><label><input name="rerank" type="checkbox" defaultChecked /> Rerank</label><button className="primary">Save pipeline</button></form>{error && <p className="form-error">{error}</p>}<div className="pipeline-list">{items.map((item) => <article key={item.id}><div><strong>{item.name} {item.is_active && "· Active"}</strong><span>v{item.version} · {item.configuration.retrieval_mode} · top {item.configuration.top_k} · threshold {item.configuration.similarity_threshold}</span></div><div className="document-actions">{!item.is_active && <button className="quiet-button" onClick={() => void activatePipeline(accessToken, projectId, item.id).then(() => setItems((current) => current.map((value) => ({...value, is_active: value.id === item.id}))))}>Activate</button>}<button className="quiet-button" onClick={() => void deletePipeline(accessToken, projectId, item.id).then(() => setItems((current) => current.filter((value) => value.id !== item.id)))}>Remove</button></div></article>)}</div><div className="document-actions"><button className="quiet-button" disabled={!items.length} onClick={download}>Export JSON</button><label className="quiet-button">Import JSON<input hidden type="file" accept="application/json,.json" onChange={(event) => upload(event.target.files?.[0])} /></label></div></section>;
}
